// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFpMLJbgiok2P8Iw9inJPYPPlcC5J9-M4',
    appId: '1:699249343274:web:cd69aa1634eca3e68ffc53',
    messagingSenderId: '699249343274',
    projectId: 'meetly-01',
    authDomain: 'meetly-01.firebaseapp.com',
    storageBucket: 'meetly-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMNx7IFOAhDwHR1LfW63tUzrWj2ZPilIo',
    appId: '1:699249343274:android:84bdcbc49f770fe08ffc53',
    messagingSenderId: '699249343274',
    projectId: 'meetly-01',
    storageBucket: 'meetly-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWEEopObuz1fZ3-nL5HCKeOe64kIuoPas',
    appId: '1:699249343274:ios:40af8099027b73698ffc53',
    messagingSenderId: '699249343274',
    projectId: 'meetly-01',
    storageBucket: 'meetly-01.firebasestorage.app',
    iosBundleId: 'com.example.meetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWEEopObuz1fZ3-nL5HCKeOe64kIuoPas',
    appId: '1:699249343274:ios:40af8099027b73698ffc53',
    messagingSenderId: '699249343274',
    projectId: 'meetly-01',
    storageBucket: 'meetly-01.firebasestorage.app',
    iosBundleId: 'com.example.meetly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFpMLJbgiok2P8Iw9inJPYPPlcC5J9-M4',
    appId: '1:699249343274:web:54cb41c55f3a156b8ffc53',
    messagingSenderId: '699249343274',
    projectId: 'meetly-01',
    authDomain: 'meetly-01.firebaseapp.com',
    storageBucket: 'meetly-01.firebasestorage.app',
  );
}
